### ISSUE TITLE
i have this erroe how do i solve it 

### ISSUE THREAD

**Issue by ValeraT17** [kirilkirkov/Ecommerce-CodeIgniter-Bootstrap#232]
An uncaught Exception was encountered
Type: Error

Message: Call to undefined method SendMail::clearAddresses()

Filename: C:\xampp\htdocs\Primedawn_Hardware\application\controllers\Checkout.php

Line Number: 72

Backtrace:

File: C:\xampp\htdocs\Primedawn_Hardware\application\controllers\Checkout.php
Line: 41
Function: sendNotifications

File: C:\xampp\htdocs\Primedawn_Hardware\index.php
Line: 292
Function: require_once

**Comment by kirilkirkov** [comment]
@ValeraT17 
Try do download/update your project. I have fixed it with this commit https://github.com/kirilkirkov/Ecommerce-CodeIgniter-Bootstrap/commit/db1e3acfa59bd716e1b9cc05a335df7871465c2c

**Comment by ValeraT17** [comment]
Hie Thank it worked. but i wanted to ask im still not receiving any mails
to the register user do i have to change something ?? for me to receive
emails

**Comment by kirilkirkov** [comment]
@ValeraT17 
You should setup your smtp server. Eg. Google

**Comment by ValeraT17** [comment]
It worked.
